name: sail_polar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  nmea: ^3.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
